### ISSUE TITLE
설치 에러가 뜹니다.

### ISSUE THREAD

**Issue by idpokute** [coska-davisville/project-cads#1]
activator run 실행시에, 잘설치되다가 에러가 뜹니다. GULP는 이미 설치되어있는 상태입니다만 아래와 같은 오류가 나오네요.

java.io.IOException: Cannot run program "gulp" (in directory "C:\project-cads"): CreateProcess error=2, 지정된 파일을 찾을 수 없습니다
        at java.lang.ProcessBuilder.start(Unknown Source)
Caused by: java.io.IOException: CreateProcess error=2, 지정된 파일을 찾을 수 없습니다
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
        at java.lang.ProcessBuilder.start(Unknown Source)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error](compile:run) java.io.IOException: Cannot run program "gulp" (in directory "C:\project-cads"): CreateProcess error=2, 지정된 파일을 찾을 수 없습니다
[error] Total time: 27 s, completed 2015. 11. 21 오후 5:51:03

**Comment by idpokute** [comment]
자답이네요. 리눅스에서 activator run실행 하면됩니다.
